### ISSUE TITLE
split_bam_and_fasta.py: Error 

### ISSUE THREAD

**Issue by Hufflepuff1012** [scottgigante/nanopore-scripts#4]
Hi!
I would like to use your script for splitting up BAM and corresponding FASTA together, in many smaller chunks.
However, although the program seems to run fine at the beginning and output a few files, it quickly runs into an error that I cannot explain. Perhaps you understand what may be wrong?

My command was:
`./split_bam_and_fasta.py -b ./Calhyp14_ToMedaka_aln.sorted.bam -f ./consensus.fasta -n 5000 --prefix SplitGenome --fasta-suffix fasta --bam-suffix bam
`

And the reported error:
```
Traceback (most recent call last):
  File "/vaults/external/asus_intel_660p_1tb/marvin/GenomePolishing/./split_bam_and_fasta.py", line 50, in <module>
    out_bams[chunk_idx[read.query_name]].write(read)
KeyError: 'A00621:678:HGCJJDSX3:1:1655:25843:33160'

```

Thank you for any help!

**Comment by scottgigante** [comment]
Hi @Hufflepuff1012 , I haven't used this in many years and don't maintain it, but just by eye it looks like that read name ('A00621:678:HGCJJDSX3:1:1655:25843:33160') exists in your BAM but not in your FASTA, leading to that error. You could put a `try: ... except KeyError: pass` around https://github.com/scottgigante/nanopore-scripts/blob/master/split_bam_and_fasta.py#L50 to just skip those reads, but you'll probably want to figure out where the mismatch comes from.

**Comment by Hufflepuff1012** [comment]
Thank you for your reply. My mistake is that I simply misunderstood the aim of your script: I wanted to split a BAM file together with the reference ( in fasta) to which the alignments were made, whereas your script aims to split a BAM together with the reads used for the alignment. Sorry for the confusion and thanks for your response! :)
